name: Sync to S3

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - 'etc/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      uses: jerryjvl/jekyll-build-action@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Deploy static site to S3 bucket
      run: aws s3 sync _site/ s3://davidmerrick.me
    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id MEI5OLP0154O --paths "/*"
